<?php namespace App\Domains\Posts;

use App\Domains\Users\UserModel;
use CodeIgniter\Model;

/**
 * PostModel Model
 *
 * Generated by Vulcan at 2017-06-27 16:23pm
 */
class PostModel extends Model
{
	protected $table      = 'posts';
	protected $primaryKey = 'id';

	protected $returnType     = 'App\Domains\Posts\Post';
	protected $useSoftDeletes = false;

	protected $allowedFields = ['forum_id', 'thread_id', 'user_id', 'type', 'title', 'body', 'html', 'deleted_at'];

	protected $useTimestamps = true;
	protected $createdField  = 'created_at';
	protected $updatedField  = 'updated_at';
	protected $dateFormat    = 'datetime';

	protected $validationRules    = [
		'id'         => 'integer|max_length[11]',
		'forum_id'   => 'integer|max_length[5]',
		'thread_id'  => 'integer|max_length[11]',
		'user_id'    => 'integer|max_length[11]',
		'title'      => 'alpha_numeric_spaces|max_length[255]',
		'body'       => '',
		'created_at' => '',
		'updated_at' => '',
		'deleted_at' => '',

	];
	protected $validationMessages = [];
	protected $skipValidation     = false;

	/**
	 * Populates the users for each post into it's $user object.
	 *
	 * @param array $posts
	 *
	 * @return array
	 */
	public function fillUsers(array $posts = [])
	{
		if (empty($posts)) return $posts;

		$userModel = new UserModel();

		// Get a list of thread ids
		$userIDs = [];
		foreach ($posts as $post)
		{
			$userIDs[] = $post->user_id;
		}
		$userIDs = array_unique($userIDs);

		// Get the posts for all of our categories
		$users = $userModel->whereIn('id', $userIDs)->findAll();

		// Grab our users with their ID as the key
		// so it's simple to fill and we use less loops
		$newUsers = [];
		foreach ($users as $user)
		{
			$newUsers[$user->id] = $user;
		}

		foreach ($posts as $post)
		{
			$post->user = $newUsers[$post->user_id];
		}

		return $posts;
	}

}
