<?php namespace App\Domains\Posts;

use CodeIgniter\Entity;
use App\Domains\Views\Theme;

/**
* A Post is a single person's part of the conversation.
*
* Generated by Vulcan at 2017-06-27 16:47:pm
*/
class Post extends Entity
{
	protected $id;
	protected $forum_id;
	protected $thread_id;
	protected $user_id;
	protected $type;
	protected $title;
	protected $body;
	protected $html;
	protected $markup;
	protected $created_at;
	protected $updated_at;
	protected $deleted_at;

	public $user;

	/**
	 * Maps names used in sets and gets against unique
	 * names within the class, allowing independence from
	 * database column names.
	 *
	 * Example:
	 *  $datamap = [
	 *      'db_name' => 'class_name'
	 *  ];
	 *
	 * @var array
	 */
	protected $datamap = [];

	//--------------------------------------------------------------------
	// Post Type Settings
	//--------------------------------------------------------------------

	/**
	 * Icon type used to determine icon displayed
	 * on the post in a post list, to quickly show it's type.
	 *
	 * @var string
	 */
	protected $iconClass = 'post-discussion-icon';

	/**
	 * The "namespaced" view that should be displayed
	 * for the form.
	 *
	 * @var string
	 */
	protected $formView = 'posts/form';

	/**
	 * The name of the view used to display the initial post in a thread.
	 *
	 * @var string
	 */
	protected $displayView = 'posts/show';

	//--------------------------------------------------------------------
	// Display Methods
	//--------------------------------------------------------------------

	/**
	 * Displays the post as the first post in a Thread.
	 */
	public function display()
	{
		return Theme::view($this->displayView, [
			'post' => $this
		]);
	}

	/**
	 * Displays the form for this post.
	 *
	 * @return string
	 */
	public function displayForm()
	{
		return Theme::view($this->formView, [
			'post' => $this
		]);
	}

}
