<?php namespace App\Domains\Posts;

use App\Domains\Users\UserManager;
use CodeIgniter\Model;
use Myth\ORM\EntityManager;

/**
 * PostModel Model
 *
 * Generated by Vulcan at 2017-06-27 16:23pm
 */
class PostManager extends EntityManager
{
	protected $table      = 'posts';
	protected $primaryKey = 'id';

	protected $returnType     = 'App\Domains\Posts\Post';
	protected $useSoftDeletes = false;

	protected $allowedFields = ['forum_id', 'thread_id', 'user_id', 'type', 'title', 'body', 'html', 'deleted_at'];

	protected $useTimestamps = true;
	protected $createdField  = 'created_at';
	protected $updatedField  = 'updated_at';
	protected $dateFormat    = 'datetime';

	protected $validationRules    = [
		'id'         => 'integer|max_length[11]',
		'forum_id'   => 'integer|max_length[5]',
		'thread_id'  => 'integer|max_length[11]',
		'user_id'    => 'integer|max_length[11]',
		'title'      => 'alpha_numeric_spaces|max_length[255]',
		'body'       => '',
		'created_at' => '',
		'updated_at' => '',
		'deleted_at' => '',

	];
	protected $validationMessages = [];
	protected $skipValidation     = false;

	protected function initialize()
	{
		$this->belongsTo(UserManager::class);
	}


}
