<?php namespace App\Domains\Users;

use CodeIgniter\Entity;

/**
 * Profile Entity
 *
 * Generated by Vulcan at 2017-09-10 23:51:pm
 */
class Profile extends Entity
{
	protected $user_id;
	protected $phone;
	protected $personal_url;
	protected $business_url;
	protected $facebook_url;
	protected $twitter_url;
	protected $gplus_url;
	protected $about;
	protected $social_public;
	protected $show_email;
	protected $show_phone;
	protected $views;
	protected $created_at;
	protected $updated_at;

	/**
	 * Maps names used in sets and gets against unique
	 * names within the class, allowing independence from
	 * database column names.
	 *
	 * Example:
	 *  $datamap = [
	 *      'db_name' => 'class_name'
	 *  ];
	 *
	 * @var array
	 */
	protected $datamap = [];
}
