<?php namespace App\Domains\Forums;

use CodeIgniter\Model;

/**
 * ForumModel Model
 *
 * Generated by Vulcan at 2017-06-27 16:23pm
 */
class ForumModel extends Model
{
	protected $table      = 'forums';
	protected $primaryKey = 'id';

	protected $returnType     = 'App\Domains\Forums\Forum';
	protected $useSoftDeletes = false;

	protected $allowedFields = ['forum_id', 'name', 'description', 'is_category', 'thread_count', 'post_count', 'last_post', 'deleted_at'];

	protected $useTimestamps = true;
	protected $createdField  = 'created_at';
	protected $updatedField  = 'updated_at';
	protected $dateFormat    = 'datetime';

	protected $validationRules    = [
		'id'            => 'integer|max_length[5]',
		'forum_id'      => 'integer',
		'name'          => 'alpha_numeric_spaces|max_length[255]',
		'description'   => 'alpha_numeric_spaces',
		'is_category'   => 'integer|max_length[1]',
		'thread_count'  => 'integer|max_length[11]',
		'post_count'    => 'integer|max_length[11]',
		'last_post'     => 'integer|max_length[11]',
		'created_at'    => '',
		'updated_at'    => '',
		'deleted_at'    => '',

	];
	protected $validationMessages = [];
	protected $skipValidation     = false;

	//--------------------------------------------------------------------

	/**
	 * Get all forums that are acting as categories.
	 *
	 * @return array|null
	 */
	public function findCategories()
	{
		return $this->findWhere('is_category', 1);
	}

	/**
	 * Populates the forums for all categories provided
	 * to skip the N+1 problem.
	 *
	 * @param array $categories
	 *
	 * @return array
	 */
	public function fillForumsIntoCategories(array $categories = [])
	{
		if (empty($categories)) return $categories;

		// Rebuild the array so that the keys are the category id for easier forum assignment.
		$newCats = [];
		foreach ($categories as $category)
		{
			$newCats[$category->id] = $category;
		}
		$categories = $newCats;
		unset($newCats);

		// Get a list of category ids
		$catIDs = [];
		foreach ($categories as $category)
		{
			$catIDs[] = $category->id;
		}

		// Get the forums for all of our categories
		$forums = $this->whereIn('forum_id', $catIDs)->findAll();

		foreach ($forums as $forum)
		{
			$categories[$forum->forum_id]->forums[$forum->id] = $forum;
		}

		return $categories;
	}


}
