<?php namespace App\Domains\Forums;

use Myth\ORM\EntityManager;

/**
 * ForumModel Model
 *
 * Generated by Vulcan at 2017-06-27 16:23pm
 */
class ForumManager extends EntityManager
{
	protected $table      = 'forums';
	protected $primaryKey = 'id';

	protected $returnType     = 'App\Domains\Forums\Forum';
	protected $useSoftDeletes = false;

	protected $allowedFields = ['forum_id', 'name', 'description', 'is_category', 'thread_count', 'post_count', 'last_post', 'deleted_at'];

	protected $useTimestamps = true;
	protected $createdField  = 'created_at';
	protected $updatedField  = 'updated_at';
	protected $dateFormat    = 'datetime';

	protected $validationRules    = [
		'id'            => 'integer|max_length[5]',
		'forum_id'      => 'integer',
		'name'          => 'alpha_numeric_spaces|max_length[255]',
		'description'   => 'alpha_numeric_spaces',
		'is_category'   => 'integer|max_length[1]',
		'thread_count'  => 'integer|max_length[11]',
		'post_count'    => 'integer|max_length[11]',
		'last_post'     => 'integer|max_length[11]',
		'created_at'    => '',
		'updated_at'    => '',
		'deleted_at'    => '',

	];
	protected $validationMessages = [];
	protected $skipValidation     = false;

	//--------------------------------------------------------------------

	protected function initialize()
	{
		$this->hasMany(ForumManager::class);
		$this->hasMany(ThreadManager::class, 'forum_id', 'id', 'threads', ['with' => 'user']);
	}

	//--------------------------------------------------------------------

	/**
	 * Get all forums that are acting as categories.
	 *
	 * @return array|null
	 */
	public function findCategories()
	{
		return $this->where('is_category', 1)->findAll();
	}

}
