<?php namespace App\Domains\Forums;

use CodeIgniter\Entity;

/**
* A Post is a single person's part of the conversation.
*
* Generated by Vulcan at 2017-06-27 16:47:pm
*/
class Post extends Entity
{
	protected $id;
	protected $forum_id;
	protected $thread_id;
	protected $user_id;
	protected $title;
	protected $body;
	protected $created_at;
	protected $updated_at;
	protected $deleted_at;

	/**
	 * Maps names used in sets and gets against unique
	 * names within the class, allowing independence from
	 * database column names.
	 *
	 * Example:
	 *  $datamap = [
	 *      'db_name' => 'class_name'
	 *  ];
	 *
	 * @var array
	 */
	protected $datamap = [];
}
