<?php namespace App\Domains\Forums;

use CodeIgniter\Entity;

/**
 * A Thread holds many posts around a single topic (hopefully!).
 * It is contained by a forum, and tracks view count and post counts.
 *
 * Generated by Vulcan at 2017-06-27 16:47:pm
 */
class Thread extends Entity
{
	protected $id;
	protected $user_id;
	protected $forum_id;
	protected $title;
	protected $first_post;
	protected $view_count;
	protected $post_count;
	protected $created_at;
	protected $updated_at;
	protected $deleted_at;

	/**
	 * A collection of posts, as filled
	 * in by the Manager class.
	 *
	 * @var array
	 */
	public $posts = [];

	/**
	 * Maps names used in sets and gets against unique
	 * names within the class, allowing independence from
	 * database column names.
	 *
	 * Example:
	 *  $datamap = [
	 *      'db_name' => 'class_name'
	 *  ];
	 *
	 * @var array
	 */
	protected $datamap = [];

	/**
	 * Generates a link to the thread-specific page.
	 *
	 * @return \CodeIgniter\Router\string|string
	 */
	public function link()
	{
		return route_to('threadLink', $this->id);
	}

}
