<?php namespace App\Domains\Forums;

use CodeIgniter\Model;

/**
 * ThreadModel Model
 *
 * Generated by Vulcan at 2017-06-27 16:23pm
 */
class ThreadModel extends Model
{
	protected $table      = 'threads';
	protected $primaryKey = 'id';

	protected $returnType     = 'array';
	protected $useSoftDeletes = false;

	protected $allowedFields = ['user_id', 'forum_id', 'title', 'first_post', 'views', 'post_count', 'deleted_at'];

	protected $useTimestamps = true;
	protected $createdField  = 'created_at';
	protected $updatedField  = 'updated_at';
	protected $dateFormat    = 'datetime';

	protected $validationRules    = [
		'id'         => 'integer|max_length[11]',
		'user_id'    => 'integer|max_length[11]',
		'forum_id'   => 'integer|max_length[5]',
		'title'      => 'alpha_numeric_spaces|max_length[255]',
		'first_post' => 'integer|max_length[11]',
		'views'      => 'integer|max_length[20]',
		'posts'      => 'integer|max_length[11]',
		'created_at' => '',
		'updated_at' => '',
		'deleted_at' => '',

	];
	protected $validationMessages = [];
	protected $skipValidation     = false;
}
